version: '3.8'

services:
  # --- Standard TLS Service --- 
  nginx-tls:
    image: nginx:latest  # Use the official Nginx image
    ports:
      - "8443:443"  # Keep the same port mapping
    volumes:
      # Mount the custom Nginx configuration
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # Mount the server certificate and key from the 'certs' subdirectory
      # to the location specified in nginx.conf (/etc/nginx/ssl/)
      - ./certs/server.crt:/etc/nginx/ssl/server.crt:ro
      - ./certs/server.key:/etc/nginx/ssl/server.key:ro

  # --- Mutual TLS (mTLS) Service --- 
  nginx-mtls:
    image: nginx:latest
    ports:
      - "8444:443" # Host port 8444
    volumes:
      # Mount the mTLS Nginx configuration
      - ./nginx-mtls.conf:/etc/nginx/nginx.conf:ro
      # Mount the server certificate, key, AND the CA cert for client verification
      - ./certs/server.crt:/etc/nginx/ssl/server.crt:ro
      - ./certs/server.key:/etc/nginx/ssl/server.key:ro
      - ./certs/client-ca.crt:/etc/nginx/ssl/client-ca.crt:ro # Mount CA cert